server:
  port: 9000

spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "prod"
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: cards
    description: "Eazybank Cards App"
    version: 1.0

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
