server:
  port: 8080

spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: "Eazybank Edge Server"
    verison: 1.0

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
