server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.config.client: DEBUG