server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: native
    # active: git
  cloud:
    config:
      server:
        native:
          # search-locations: "classpath:/config"
          search-locations: "file:///C:/Users/iss211/microservices-springboot/config/"
        # git:
        #   uri: https://github.com/eazybytes/eazybytes-config.git
        #   default-label: main
        #   timeout: 5
        #   clone-on-start: true
        #   force-pull: true
encrypt:
  key: "45JFCNNSDDHOISWWE1490903"