
build:
  version: "2.0"

accounts:
  message: "Welcome to Eazybank accounts related QA API's"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (555)265-1234
    - (555)265-1235